### ISSUE TITLE
I need a screenshot of your editor.

### ISSUE THREAD

**Issue by bemoregt** [fredo-editor/FreDo#1]
Hi, @vighneshbirodkar 

This may be good editor.
but,
I need a screenshot of your editor.

Thanks.

**Comment by yasiupl** [comment]
https://fredo-editor.github.io/

**Comment by yasiupl** [comment]
@vighneshbirodkar Consider adding an [URL of the GitHub Pages website](https://fredo-editor.github.io) to the sidebar in this repository. 

![image](https://user-images.githubusercontent.com/12561099/147684876-1d42c619-84bc-479b-b6f8-df4d1590b648.png)
